UNKNOWN_ERROR:
  code: 1000300
  message: "未知错误"
  developer_message: "Unknown error: {error}"

BAD_REQUEST:
  code: 1000400
  message: "请求错误或参数异常"
  developer_message: "Request failed or parameter exception: {error}"

UNAUTHORIZED:
  code: 1000401
  message: "认证失败"
  developer_message: "Authentication failed: {error}"

NOT_FOUND:
  code: 1000404
  message: "资源不存在"
  developer_message: "{resource} was not found."

INTERNAL_SERVER_ERROR:
  code: 1000500
  message: "服务内部异常"
  developer_message: "Internal server error: {error}"

